/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d1565d55-7abd-4caf-a203-512d6049c667",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KRLGC4mf7",
    "aws_user_pools_web_client_id": "58m7qnoovlvbn84v08641ok016",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ylpufnx2tnbndnjfrjppqhqbo4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tokwxzimcjgmbbusvvi5kdliq4",
    "aws_user_files_s3_bucket": "storageamplifyapp84911-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
